<?php
/* 
lylina news aggregator

Copyright (C) 2006 Eric Harmon

Upgrade Script: 1.21 -> 1.22

lylina is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

lylina is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with lylina; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

verify_upgrade($upgrade_bit);

$temp = check_version($conf['version'],"1.21");
if($temp == -1)
	require_once('installer/upgrade111.php');
elseif($temp == 1)
	die('Upgrade error, expected v1.21, got v' . $conf['version']);

print 'Please wait while the installer upgrades lylina (1.21->1.22)...<br />';

$file = fopen('conf.php','w+') or die('Upgrade error, unable to open conf.php, please check if file exists and permissions are set correctly!');
fwrite($file,'<?php
// Welcome to lylina

// This file was automatically generated by the installer.

// =============================================================
//
// The following options MUST be changed in order for lylina to
// work correctly.
//
// =============================================================

// -------------------- MySQL Configuration --------------------
// This tells lylina which database to store information in.

$conf[\'db_host\']     = \'' . $conf['db_host'] . '\';
$conf[\'db_user\']     = \'' . $conf['db_user'] . '\';
$conf[\'db_pass\']     = \'' . $conf['db_pass'] . '\';
$conf[\'db_database\'] = \'' . $conf['db_database'] . '\';

// =============================================================
//
// The following options allow you to futher customize lylina
//
// =============================================================

// ----------------------- Display Mode  -----------------------
// This will allow you to configure which "display mode" to use
// with lylina. Valid settings are: "normal" - multiuser system,
// "login" - multiuser requiring login to use, "single" - a
// single user system requiring login only to edit sources.

$conf[\'mode\']        = \'' . $conf['mode'] . '\';

// ------------------------ Page Title -------------------------
// Sets the titlebar for the page

$conf[\'page_title\']  = \'' . $conf['page_title'] . '\';

// ---------------------- RSS Description ----------------------
// Chooses the description for the RSS feed

$conf[\'rss_desc\']    = \'' . $conf['rss_desc'] . '\';

// ------------------------- Page Logo -------------------------
// Allows you to change the logo seen in the page

$conf[\'page_logo\']   = \'' . $conf['page_logo'] . '\';

// -------------------------- Language -------------------------
// Contols the language used by lylina.
// Languages must be in the \'lang\' folder, and must use the
// ISO language code, ie: \'en.inc.php\'

$conf[\'language\']    = \'' . $conf['language'] . '\';

// -------------------------- Use Cron -------------------------
// Set this option to false if you are not using a cron job.
// Note that this slows page loading speeds drastically.

$conf[\'usecron\']     = \'' . $conf['usecron'] . '\';

// ------------------------- Page Style ------------------------
// Allows you to choose the CSS skin used to theme the page.
// This file MUST be in the \'style\' folder.

$conf[\'page_style\']  = \'' . $conf['page_style'] . '\';

// -------------------------- Sources --------------------------
// Controls the display of sources at the bottom of the page

$conf[\'sources\']     = \'' . $conf['sources'] . '\';

// -------------------- Digg.com integration -------------------
// Adds a "submit to digg" link to each post, letting you
// quickly post it to digg.com

$conf[\'digg\']        = \'' . $conf['digg'] . '\';

// ------------------- del.icio.us integration -----------------
// Adds an "add to del.icio.us" link to each post, letting you
// post it quickly to your social bookmarks.

$conf[\'del.icio.us\'] = \'' . $conf['del.icio.us'] . '\';

// --------------------- reddit integration --------------------
// Adds a "submit to reddit" link to each post, letting you
// post it quickly to reddit

$conf[\'reddit\']      = \'' . $conf['reddit'] . '\';

// ---------------------- furl integration ---------------------
// Adds an "add to furl" link to each post, letting you submit
// the item to your furl bookmarks

$conf[\'furl\']        = \'' . $conf['furl'] . '\';

// -------------------- newsvine integration -------------------
// Adds a "seed at newsvine" link to each post, letting you 
// easy seed the newsvine.

$conf[\'newsvine\']        = \'' . $conf['newsvine'] . '\';

// ---------------- Open News Links in New Window --------------
// Turn this on to force links to news items to open in new
// browser windows.

$conf[\'new_window\']  = \'' . $conf['new_window'] . '\';

// -------------------------- Search ---------------------------
// Enabled or disable the search function

$conf[\'search\']      = \'' . $conf['search'] . '\';

// =============================================================
//
// The following options ARE FOR ADVANCED USERS ONLY.
// These options allow for powerful adjustments to how lylina
// works, and should only be used by advanced users.
//
// =============================================================

// ------------------------- Debug Mode ------------------------
// This setting will turn on debugging mode for item fetching.

$conf[\'debug\']       = \'' . $conf['debug'] . '\';

// --------------------- Password Encryption -------------------
// This sets the password encryption scheme in lylina. DO NOT
// CHANGE THIS SETTING AFTER YOU SETUP USERS IN LYLINA. No users
// will be able to login. By default lylina sets up the admin
// user with a smd5 encrypted password, thus, you will have to
// change this manually in MySQL. It is not suggested you change
// this setting.
// 
// Valid encryption schemes: smb5, md5, sha1, ssha, crypt, mysql,
// my411

$conf[\'passcrypt\']   = \'' . $conf['passcrypt'] . '\';

// ---------------------- HTMLSax3 location --------------------
// Specifies the location of the HTMLSax3 library. This is
// installed by lylina, thus, should not require modification.

define(\'XML_HTMLSAX3\',\'' . XML_HTMLSAX3 . '\');

// ------------------ MagpieRSS Cache Directory ----------------
// Specifies the location where MagpieRSS should cache feeds.
// This should never require modification.

define(\'MAGPIE_CACHE_DIR\', \'' . MAGPIE_CACHE_DIR . '\');

// -------------------------- Version --------------------------
// This tells the lylina installer which version of lylina you
// currently have installed.

$conf[\'version\']     = \'' . $version . '\';

?>
') or die('Upgrade error, unable to write to conf.php, please check permissions!');
fclose($file);
print 'Configuration file written...<br />';
}
?>